global_frame: map
rolling_window: false
track_unknown_space: true

#膨胀层：做动态路径规划时，计算与障碍物的距离的代价值
inflation:
    inflation_radius: 0.2

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: rgbd_obstacle_layer,              type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
